export enum ReduxActionTypes {
    ADD_RESIDENT = 'ADD_RESIDENT',
    UPDATE_RESIDENT = 'UPDATE_RESIDENT',
    DELETE_RESIDENT = 'DELETE_RESIDENT',
    ADD_CONTACT ='ADD_CONTACT',
    UPDATE_CONTACT = 'UPDATE_CONTACT',
    DELETE_CONTACT = 'DELETE_CONTACT',
    ADD_CONTACT_TO_RESIDENT = 'ADD_CONTACT_TO_RESIDENT',
    ADD_CONTACT_TO_CONTACT = 'ADD_CONTACT_TO_CONTACT',
    CREATE_USER = 'CREATE_USER',
    MAKE_ACTIVE_USER = 'MAKE_ACTIVE_USER'
}